# When making changes to this file update requirements.txt also !!
# Usage: conda -v env update -n bluepy3 --file environment.yml

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - tomli
  - pip
  # Not on conda channels:
  - pip:
      - pylint
