# When making changes to this file update requirements.txt also !!
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: bluepy3

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - clang-format
  - cpplint
  - tomli
  - pip
  - pre-commit
  # Not on conda channels:
  - pip:
      - pylint
