# When making changes to this file update requirements.txt also !!
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: bluepy3

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  # imported deps
  - tomli=2.0.1

  # dev deps
  - clang-format
  - cpplint
  - pipdeptree
  - pre-commit
  - pylint>=3.0.2
